# Generated by Django 5.0 on 2024-07-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
