# Generated by Django 5.0 on 2024-02-29 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elapsed_time', models.FloatField()),
                ('completion_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HazardRatesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('susceptible', models.IntegerField()),
                ('infectious', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('vaccinated', models.IntegerField()),
                ('hospitalized', models.IntegerField()),
                ('removed', models.IntegerField()),
                ('associated_data_id', models.PositiveIntegerField()),
                ('associated_data_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'simulation'), ('model', 'healthauthoritydata')), models.Q(('app_label', 'simulation'), ('model', 'homecommunitydata')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='HomeCommunityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_home_community_id', models.IntegerField()),
                ('simulation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_community_data', to='simulation.simulationresult')),
            ],
        ),
        migrations.CreateModel(
            name='HealthAuthorityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_health_authority_id', models.IntegerField()),
                ('simulation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_authority_data', to='simulation.simulationresult')),
            ],
        ),
    ]
