# Generated by Django 5.0 on 2024-03-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_simulationresult_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationresult',
            name='completion_time',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='elapsed_time',
        ),
    ]
