# Generated by Django 5.0 on 2024-03-23 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_remove_simulationresult_completion_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatePopulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_population_data', to='simulation.simulationresult')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationHazardRatesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('susceptible', models.IntegerField()),
                ('infectious', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('vaccinated', models.IntegerField()),
                ('hospitalized', models.IntegerField()),
                ('removed', models.IntegerField()),
                ('aggregate_population_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_hazard_rates_data', to='simulation.aggregatepopulationdata')),
            ],
        ),
    ]
