# Generated by Django 5.0 on 2024-02-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario_name", models.CharField(max_length=200)),
                ("input_dir", models.CharField(default="", max_length=200)),
                ("output_dir", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
