# Generated by Django 5.0 on 2024-02-10 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_configuration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobconfiguration",
            name="disease_parameters",
            field=models.FileField(default="", upload_to="disease_parameters/"),
        ),
        migrations.AddField(
            model_name="jobconfiguration",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jobconfiguration",
            name="simulation_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobconfiguration",
            name="scenario_name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
