# Generated by Django 5.0 on 2024-02-10 02:31

import job_configuration.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_configuration", "0002_jobconfiguration_disease_parameters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobconfiguration",
            name="disease_parameters",
            field=models.FileField(
                default="",
                upload_to="disease_parameters/",
                validators=[
                    job_configuration.validators.validate_file_extension
                ],
            ),
        ),
    ]
