# Generated by Django 5.0 on 2024-02-11 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_configuration", "0003_alter_jobconfiguration_disease_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobconfiguration",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 2, 11, 23, 50, 38, 400069, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobconfiguration",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
