# Generated by Django 5.0 on 2024-02-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_configuration", "0004_jobconfiguration_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobconfiguration",
            name="test_file",
            field=models.FileField(default="", upload_to=""),
        ),
        migrations.AddField(
            model_name="jobconfiguration",
            name="test_file2",
            field=models.FileField(default="", upload_to=""),
        ),
    ]
