# Generated by Django 5.0 on 2024-03-06 18:02

from job_configuration.models import File
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_configuration", "0008_file_created_at_alter_file_job_configuration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobconfiguration",
            name="input_dir",
        ),
        migrations.RemoveField(
            model_name="jobconfiguration",
            name="output_dir",
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                upload_to=File.upload_file_path
            ),
        ),
    ]
    