# Generated by Django 5.0 on 2024-10-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_configuration', '0010_rename_simulation_days_jobconfiguration_number_of_simulations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobconfiguration',
            name='description',
            field=models.CharField(default='job configuration description', max_length=800),
        ),
    ]
