# Generated by Django 5.0 on 2024-02-13 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_job_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='commandable_by',
            field=models.ManyToManyField(blank=True, related_name='commandable_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='readable_by',
            field=models.ManyToManyField(blank=True, related_name='readable_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
