# Generated by Django 5.0 on 2024-02-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_commandable_by_job_readable_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('NOT_QUEUED', 'NOT_QUEUED'), ('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('FINISHED', 'FINISHED'), ('FAILED', 'FAILED')], default='NOT_QUEUED', max_length=10),
        ),
    ]
