# Generated by Django 5.0 on 2024-02-15 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='readable_by',
            new_name='readers',
        ),
        migrations.RemoveField(
            model_name='job',
            name='commandable_by',
        ),
        migrations.AddField(
            model_name='job',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
