# Generated by Django 5.0 on 2024-03-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0008_alter_job_job_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="batch_job_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
