# Generated by Django 5.0 on 2024-03-10 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0009_alter_job_job_configuration"),
        ("job", "0009_job_batch_job_id"),
    ]

    operations = []
