# Generated by Django 5.0 on 2024-03-10 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0010_merge_20240310_0214"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobConfiguration",
        ),
    ]
