# Generated by Django 5.0 on 2024-03-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0012_job_log_stream_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="queue_time",
        ),
    ]
