# Generated by Django 5.0 on 2024-05-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_remove_job_queue_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='number_of_simulations',
            field=models.IntegerField(default=0),
        ),
    ]
