# Generated by Django 5.0 on 2024-07-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_job_number_of_simulations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('NOT_QUEUED', 'NOT_QUEUED'), ('QUEUED', 'QUEUED'), ('FINISHED', 'FINISHED'), ('SUBMITTED', 'SUBMITTED'), ('PENDING', 'PENDING'), ('RUNNABLE', 'RUNNABLE'), ('STARTING', 'STARTING'), ('RUNNING', 'RUNNING'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], default='NOT_QUEUED', max_length=10),
        ),
    ]
